title: Project Plants
description: The open-source plants manager
theme: just-the-docs
repository: Project-Plants-App/Project-Plants-App.github.io

url: https://project-plants.ch
baseurl: ''

search_enabled: false
search.heading_level: 3
logo: "/assets/images/logo.png"

include: [ CNAME ]

aux_links:
  "GitHub":
    - "https://github.com/Project-Plants-App"
aux_links_new_tab: true